x-service: &default-service
  image: holaflenain/stable-diffusion:latest
  runtime: nvidia
  volumes:
    - '/data/stable-diffusion:/config:rw'
  

x-environment: &default-environment
  NVIDIA_VISIBLE_DEVICES: all
  TZ: ${TZ:-America/New_York}
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}

x-labels: &default-labels
  - traefik.enable=true
  - traefik.http.routers.ollama.entrypoints=websecure
  - traefik.http.services.ollama.loadbalancer.server.port=9000
  - com.centurylinklabs.watchtower.enable=true
  - autoheal=true

  

services:
  stable-diffusion-easy-diffusion:
    <<: *default-service
    profiles: [easy-diffusion]
    container_name: stable-diffusion-easy-diffusion
    environment:
      <<: *default-environment
      WEBUI_VERSION: '01'
    labels:
      - joyride.host.name=easy-diffusion.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.easy-diffusion.entrypoints=websecure
      - traefik.http.routers.easy-diffusion.rule=Host(`easy-diffusion.traefikturkey.icu`)
      - traefik.http.services.easy-diffusion.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true
      

  stable-diffusion-automatic:
    <<: *default-service
    profiles: [automatic]
    container_name: stable-diffusion-automatic
    environment:
      <<: *default-environment
      WEBUI_VERSION: '02'
    labels:
      - joyride.host.name=automatic.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.automatic.entrypoints=websecure
      - traefik.http.routers.automatic.rule=Host(`automatic.traefikturkey.icu`)
      - traefik.http.services.automatic.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-forge:
    <<: *default-service
    profiles: [forge]
    container_name: stable-diffusion-forge
    environment:
      <<: *default-environment
      WEBUI_VERSION: '02.forge'
    labels:
      - joyride.host.name=forge.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.forge.entrypoints=websecure
      - traefik.http.routers.forge.rule=Host(`forge.traefikturkey.icu`)
      - traefik.http.services.forge.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-invoke-ai:
    <<: *default-service
    profiles: [invoke-ai]
    container_name: stable-diffusion-invoke-ai
    environment:
      <<: *default-environment
      WEBUI_VERSION: '03'
    labels:
      - joyride.host.name=invoke-ai.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.invoke-ai.entrypoints=websecure
      - traefik.http.routers.invoke-ai.rule=Host(`invoke-ai.traefikturkey.icu`)
      - traefik.http.services.invoke-ai.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-sd-next:
    <<: *default-service
    profiles: [sd-next]
    container_name: stable-diffusion-sd-next
    environment:
      <<: *default-environment
      WEBUI_VERSION: '04'
    labels:
      - joyride.host.name=sd-next.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.sd-next.entrypoints=websecure
      - traefik.http.routers.sd-next.rule=Host(`sd-next.traefikturkey.icu`)
      - traefik.http.services.sd-next.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-comfy-ui:
    <<: *default-service
    profiles: [comfy-ui]
    container_name: stable-diffusion-comfy-ui
    environment:
      <<: *default-environment
      WEBUI_VERSION: '05'
    labels:
      - joyride.host.name=comfy-ui.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.comfy-ui.entrypoints=websecure
      - traefik.http.routers.comfy-ui.rule=Host(`comfy-ui.traefikturkey.icu`)
      - traefik.http.services.comfy-ui.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-fooocus:
    <<: *default-service
    profiles: [fooocus]
    container_name: stable-diffusion-fooocus
    environment:
      <<: *default-environment
      WEBUI_VERSION: '06'
    labels:
      - joyride.host.name=fooocus.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.fooocus.entrypoints=websecure
      - traefik.http.routers.fooocus.rule=Host(`fooocus.traefikturkey.icu`)
      - traefik.http.services.fooocus.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-stable-swarm:
    <<: *default-service
    profiles: [stable-swarm]
    container_name: stable-diffusion-stable-swarm
    environment:
      <<: *default-environment
      WEBUI_VERSION: '07'
    labels:
      - joyride.host.name=stable-swarm.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.stable-swarm.entrypoints=websecure
      - traefik.http.routers.stable-swarm.rule=Host(`stable-swarm.traefikturkey.icu`)
      - traefik.http.services.stable-swarm.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-lama-cleaner:
    <<: *default-service
    profiles: [lama-cleaner]
    container_name: stable-diffusion-lama-cleaner
    environment:
      <<: *default-environment
      WEBUI_VERSION: '50'
    labels:
      - joyride.host.name=lama-cleaner.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.lama-cleaner.entrypoints=websecure
      - traefik.http.routers.lama-cleaner.rule=Host(`lama-cleaner.traefikturkey.icu`)
      - traefik.http.services.lama-cleaner.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-face-fusion:
    <<: *default-service
    profiles: [face-fusion]
    container_name: stable-diffusion-face-fusion
    environment:
      <<: *default-environment
      WEBUI_VERSION: '51'
    labels:
      - joyride.host.name=face-fusion.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.face-fusion.entrypoints=websecure
      - traefik.http.routers.face-fusion.rule=Host(`face-fusion.traefikturkey.icu`)
      - traefik.http.services.face-fusion.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true

  stable-diffusion-kohya:
    <<: *default-service
    profiles: [kohya] 
    container_name: stable-diffusion-kohya
    environment:
      <<: *default-environment
      WEBUI_VERSION: '70'
    labels:
      - joyride.host.name=kohya.traefikturkey.icu
      - traefik.enable=true
      - traefik.http.routers.kohya.entrypoints=websecure
      - traefik.http.routers.kohya.rule=Host(`kohya.traefikturkey.icu`)
      - traefik.http.services.kohya.loadbalancer.server.port=9000
      - com.centurylinklabs.watchtower.enable=true
      - autoheal=true